In [1]:
import numpy as np
import arrayfire as af

In [2]:
a = np.random.rand(2,5)
a = af.to_array(a)

In [3]:
a[0, :] = af.Array([1, 2, 3, 4, 5])
a[1, :] = af.Array([10, 20, 30, 40, 50])

In [4]:
a

arrayfire.Array()
Type: double
[2 5 1 1]
    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 


In [5]:
b = af.tile(a,1, 1, 5)

In [6]:
b
    

arrayfire.Array()
Type: double
[2 5 5 1]
    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 



In [7]:
b

arrayfire.Array()
Type: double
[2 5 5 1]
    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 



In [8]:
c = af.to_array(np.swapaxes(b, 1, 2))

In [9]:
c

arrayfire.Array()
Type: double
[2 5 5 1]
    1.0000     1.0000     1.0000     1.0000     1.0000 
   10.0000    10.0000    10.0000    10.0000    10.0000 

    2.0000     2.0000     2.0000     2.0000     2.0000 
   20.0000    20.0000    20.0000    20.0000    20.0000 

    3.0000     3.0000     3.0000     3.0000     3.0000 
   30.0000    30.0000    30.0000    30.0000    30.0000 

    4.0000     4.0000     4.0000     4.0000     4.0000 
   40.0000    40.0000    40.0000    40.0000    40.0000 

    5.0000     5.0000     5.0000     5.0000     5.0000 
   50.0000    50.0000    50.0000    50.0000    50.0000 



In [10]:
c[0, :, 0]

arrayfire.Array()
Type: double
[1 5 1 1]
    1.0000     1.0000     1.0000     1.0000     1.0000 

In [11]:
c[0,:,:]

arrayfire.Array()
Type: double
[1 5 5 1]
    1.0000     1.0000     1.0000     1.0000     1.0000 

    2.0000     2.0000     2.0000     2.0000     2.0000 

    3.0000     3.0000     3.0000     3.0000     3.0000 

    4.0000     4.0000     4.0000     4.0000     4.0000 

    5.0000     5.0000     5.0000     5.0000     5.0000 



In [12]:
b

arrayfire.Array()
Type: double
[2 5 5 1]
    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 

    1.0000     2.0000     3.0000     4.0000     5.0000 
   10.0000    20.0000    30.0000    40.0000    50.0000 



In [13]:
d = af.data.reorder(b, 0, 2, 1)

In [14]:
d

arrayfire.Array()
Type: double
[2 5 5 1]
    1.0000     1.0000     1.0000     1.0000     1.0000 
   10.0000    10.0000    10.0000    10.0000    10.0000 

    2.0000     2.0000     2.0000     2.0000     2.0000 
   20.0000    20.0000    20.0000    20.0000    20.0000 

    3.0000     3.0000     3.0000     3.0000     3.0000 
   30.0000    30.0000    30.0000    30.0000    30.0000 

    4.0000     4.0000     4.0000     4.0000     4.0000 
   40.0000    40.0000    40.0000    40.0000    40.0000 

    5.0000     5.0000     5.0000     5.0000     5.0000 
   50.0000    50.0000    50.0000    50.0000    50.0000 



In [16]:
af.flat(d)

arrayfire.Array()
Type: double
[50 1 1 1]
    1.0000 
   10.0000 
    1.0000 
   10.0000 
    1.0000 
   10.0000 
    1.0000 
   10.0000 
    1.0000 
   10.0000 
    2.0000 
   20.0000 
    2.0000 
   20.0000 
    2.0000 
   20.0000 
    2.0000 
   20.0000 
    2.0000 
   20.0000 
    3.0000 
   30.0000 
    3.0000 
   30.0000 
    3.0000 
   30.0000 
    3.0000 
   30.0000 
    3.0000 
   30.0000 
    4.0000 
   40.0000 
    4.0000 
   40.0000 
    4.0000 
   40.0000 
    4.0000 
   40.0000 
    4.0000 
   40.0000 
    5.0000 
   50.0000 
    5.0000 
   50.0000 
    5.0000 
   50.0000 
    5.0000 
   50.0000 
    5.0000 
   50.0000 
